remote_theme: pages-themes/minimal@v0.2.0
plugins:
<<<<<<< HEAD
- jekyll-remote-theme # add this line to the plugins list if you already have one
=======
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Benji Copan
description: Personal website for full stack developer Benji Copan
theme: jekyll-theme-minimal
>>>>>>> 770ebf26e8bcd2e290dd68181d07c4f7f7c427f9
